version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserverbulkinsert_test_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MyStrongPassw0rd
    ports:
      - "14330:1433"
    restart: unless-stopped